imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     %database_path%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

security:
    firewalls:
        # replace 'main' by the name of your own firewall
        secured_api:
            security: false

hautelook_alice:
    locale: 'fr_FR'
    seed: 1

fos_elastica:
    indexes:
        partner:
            types:
                partner:
                    persistence:
                        listener:
                            enabled: false
                partner_registry_user:
                    persistence:
                        listener:
                            enabled: false
                company_registry_user:
                    persistence:
                        listener:
                            enabled: false
        test_partner:
            types:
                partner:
                    properties:
                        id:
                            type: integer
                        type:
                            type: string
                        contractNumber:
                            type: string
                        corporateName:
                            type: string
                        commercialName:
                            type: string
                        kvpsNumber:
                            type: string
                        webSite:
                            type: string
                        isPartnerR8:
                            type: boolean
                        isTwinService:
                            type: boolean
                        isPartnerPlus:
                            type: boolean
                        isOccPlus:
                            type: boolean
                        occPlusContractNumber:
                            type: string
                        isEtron:
                            type: boolean
                        siteType:
                            type: string
                        category:
                            type: string
                        representationType:
                            type: string
                        prestigeType:
                            type: string
                        dealersMeeting:
                            type: boolean
                        brandDays:
                            type: boolean
                        rent:
                            type: boolean
                        extraHour:
                            type: boolean
                        ferMembership:
                            type: boolean
                        onlineQuotation:
                            type: boolean
                        amexPayment:
                            type: boolean
                        isDigitAll:
                            type: boolean
                        digitAllId:
                            type: string
                        isV12:
                            type: boolean
                        v12Id:
                            type: string
                        sellingVolume:
                            type: integer
                        group:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                                websiteUrl:
                                    type: string
                                status:
                                    type: integer
                        region:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                                partnerType:
                                    type: string
                        district:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                        legacyId:
                            type: integer
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: PartnerBundle\Entity\Partner
                        finder: ~
                        provider: ~
                        listener: ~

                partner_registry_user:
                    properties:
                        id:
                            type: integer
                        registryUserId:
                            type: integer
                        partner:
                            type: object
                            properties:
                                id:
                                    type: integer
                                type:
                                    type: string
                                contractNumber:
                                    type: string
                                corporateName:
                                    type: string
                                commercialName:
                                    type: string
                                kvpsNumber:
                                    type: string
                                webSite:
                                    type: string
                                isPartnerR8:
                                    type: boolean
                                isTwinService:
                                    type: boolean
                                isPartnerPlus:
                                    type: boolean
                                isOccPlus:
                                    type: boolean
                                occPlusContractNumber:
                                    type: string
                                isEtron:
                                    type: boolean
                                siteType:
                                    type: string
                                category:
                                    type: string
                                representationType:
                                    type: string
                                prestigeType:
                                    type: string
                                dealersMeeting:
                                    type: boolean
                                brandDays:
                                    type: boolean
                                rent:
                                    type: boolean
                                extraHour:
                                    type: boolean
                                ferMembership:
                                    type: boolean
                                onlineQuotation:
                                    type: boolean
                                amexPayment:
                                    type: boolean
                                isDigitAll:
                                    type: boolean
                                digitAllId:
                                    type: string
                                isV12:
                                    type: boolean
                                v12Id:
                                    type: string
                                sellingVolume:
                                    type: integer
                                group:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        name:
                                            type: string
                                        websiteUrl:
                                            type: string
                                        status:
                                            type: integer
                                region:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        name:
                                            type: string
                                        partnerType:
                                            type: string
                                district:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        name:
                                            type: string
                                legacyId:
                                    type: integer
                                createdAt:
                                    type: date
                                updatedAt:
                                    type: date
                        department:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                        position:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                        positionCode:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                        region:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                                partnerType:
                                    type: string
                        district:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                        isAdmin:
                            type: boolean
                        vision:
                            type: boolean
                        dealersMeeting:
                            type: boolean
                        brandDays:
                            type: boolean
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: PartnerBundle\Entity\PartnerRegistryUser
                        finder: ~
                        provider: ~
                        listener: ~

                company_registry_user:
                    properties:
                        id:
                            type: integer
                        registryUserId:
                            type: integer
                        company:
                            type: object
                            properties:
                                id:
                                    type: integer
                                type:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        name:
                                            type: string
                                        status:
                                            type: integer
                                corporateName:
                                    type: string
                                commercialName:
                                    type: string
                                status:
                                    type: integer
                                legacyId:
                                    type: integer
                                createdAt:
                                    type: date
                                updatedAt:
                                    type: date
                        department:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                        position:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                        positionCode:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                        positionDescription:
                            type: string
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: PartnerBundle\Entity\CompanyRegistryUser
                        finder: ~
                        provider: ~
                        listener: ~
