imports:
    - { resource: config_dev.yml }

parameters:
    partner_index_name: test_partner

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     %database_path%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

hautelook_alice:
    locale: 'fr_FR'
    seed: 1
