partners_api:
    resource: PartnerBundle\Controller\PartnerController
    type:     rest
    prefix:   /

partner_registry_user:
    resource: PartnerBundle\Controller\PartnerRegistryUserController
    type:     rest
    prefix:   /registry

company_registry_user:
    resource: PartnerBundle\Controller\CompanyRegistryUserController
    type:     rest
    prefix:   /company/registry

company_department:
    resource: PartnerBundle\Controller\CompanyDepartmentController
    type:     rest
    prefix:   /company/department

company_position:
    resource: PartnerBundle\Controller\CompanyPositionController
    type:     rest
    prefix:   /company/position

region:
    resource: PartnerBundle\Controller\RegionController
    type:     rest
    prefix:   /region

