# app/config/security.yml
security:
    providers:
        auth_user_provider:
            id: Mullenlowe\CommonBundle\Security\User\AuthUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:  ^/
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - Mullenlowe\CommonBundle\Security\Guard\JWTTokenAuthenticator

    access_control:
        - { path: ^/myaudi,           role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/ekino/,           role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST, GET] }
        - { path: ^/opening-hour/,    role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/\d+/deposit/,     role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/,                 role: IS_AUTHENTICATED_FULLY }
