# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        jwt:
            lexik_jwt:
                class: \Mullenlowe\CommonBundle\Security\User\JwtUser

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_api:
            pattern: ^/api/v1
            provider: jwt
            guard:
                authenticators:
                    - 'mullenlowe.commonbundle.jwt_json_token_authenticator'
            anonymous:    true
            stateless: true
            entry_point: 'mullenlowe.commonbundle.jwt_json_token_authenticator'

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/api/v1, role: ROLE_USER }
