<?php

namespace PartnerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use PartnerBundle\Entity\Partner;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends EntityRepository
{
    /**
     * @param integer $myaudiUserId
     * @return null|Partner
     */
    public function findOneByMyaudiUserId($myaudiUserId)
    {
        $result = $this->createQueryBuilder('p')
            ->addSelect('p')
            ->innerJoin('p.myaudiUsers', 'u')
            ->add('where', 'u.myaudiUserId=:myaudi_user_id')
            ->setParameter('myaudi_user_id', $myaudiUserId)
            ->getQuery()
            ->getResult();

        if (isset($result[0])) {
            return $result[0];
        }

        return null;
    }
}
