services:
#    partner.example:
#        class: PartnerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    PartnerBundle\Service\MyaudiUserCreateOrUpdatePartnerConsumer:
          arguments:
              $logger: '@monolog.logger.request'
              $em: '@doctrine.orm.entity_manager'