<?php

namespace PartnerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PartnerBundle\Entity\Partner;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends EntityRepository
{
    const CDV = 'CDV';

    /**
     * @param integer $myaudiUserId
     * @return null|Partner
     */
    public function findOneByMyaudiUserId($myaudiUserId)
    {
        $result = $this->createQueryBuilder('p')
            ->addSelect('p')
            ->innerJoin('p.myaudiUsers', 'u')
            ->add('where', 'u.myaudiUserId=:myaudi_user_id')
            ->setParameter('myaudi_user_id', $myaudiUserId)
            ->getQuery()
            ->getResult();

        if (isset($result[0])) {
            return $result[0];
        }

        return null;
    }

    /**
     * @param integer $registryUserId
     * @return null|Partner
     */
    public function findOneByRegistryUserId($registryUserId)
    {
        $result = $this->createQueryBuilder('p')
            ->addSelect('p')
            ->innerJoin('p.registryUsers', 'u')
            ->add('where', 'u.registryUserId=:registry_user_id')
            ->setParameter('registry_user_id', $registryUserId)
            ->getQuery()
            ->getResult();

        if (isset($result[0])) {
            return $result[0];
        }

        return null;
    }

    /**
     * @param int|null    $registryUserId
     * @param int|null    $myaudiUserId
     * @param string|null $partnerIds
     * @return \Doctrine\ORM\Query
     */
    public function findPartnersByCustomFilters($registryUserId = null, $myaudiUserId = null,
        $partnerIds = null, $region = null, $district = null)
    {
        $queryBuilder = $this->createQueryBuilder('partner');

        if ($registryUserId) {
            $queryBuilder
                ->join('partner.registryUsers', 'registryUsers')
                ->andWhere('registryUsers.registryUserId = :registryUserId')
                ->setParameter('registryUserId', $registryUserId);
        }

        if ($myaudiUserId) {
            $queryBuilder
                ->join('partner.myaudiUsers', 'myaudiUsers')
                ->andWhere('myaudiUsers.myaudiUserId = :myaudiUserId')
                ->setParameter('myaudiUserId', $myaudiUserId);
        }

        if ($partnerIds) {
            $ids = explode(',', $partnerIds);
            $queryBuilder
                ->andWhere('partner.id IN (:ids)')
                ->setParameter('ids', $ids);
        }

        if ($region) {
            $queryBuilder
                ->andWhere('partner.region = :region')
                ->setParameter('region', $region);
        }

        if ($district) {
            $queryBuilder
                ->andWhere('partner.district = :district')
                ->setParameter('district', $district);
        }

        return $queryBuilder->getQuery();
    }
}
